# Generated by Django 5.1.3 on 2024-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_delete_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admission_number',
            field=models.CharField(default=234234, max_length=10),
            preserve_default=False,
        ),
    ]
